name: Node.js CI

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '22.13.1'
      test-command:
        required: false
        type: string
        default: 'npm run test:coverage'
      eslint-command:
        required: false
        type: string
        default: 'npx eslint .'
      install-command:
        required: false
        type: string
        default: 'npm install'
      fetch-depth:
        required: false
        type: string
        default: '0'
    secrets:
      SONAR_TOKEN:
        required: true
      GITHUB_TOKEN_SECRET:
        required: false

jobs:
  test-and-sonar:
    name: Tests and SonarQube
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: ${{ inputs.install-command }}

      - name: Run tests with coverage
        run: ${{ inputs.test-command }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_SECRET }}
        with:
          args: >
            -Dsonar.pullrequest.key=${{ github.event.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.pullrequest.provider=GitHub
            -Dsonar.pullrequest.github.repository=${{ github.repository }}
            -Dsonar.pullrequest.github.endpoint=${{ github.api_url }}
            -Dsonar.pullrequest.github.token.secured=${{ secrets.GITHUB_TOKEN_SECRET }}
            -Dsonar.pullrequest.github.repository.organization=${{ github.repository_owner }}
            -Dsonar.pullrequest.github.repository.name=${{ github.event.repository.name }}

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 5

  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: ${{ inputs.install-command }}

      - name: Run ESLint
        run: ${{ inputs.eslint-command }}

